name: Build and Push Docker Image, Notify via Webhook

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./Spletno programiranje/Backend
          file: ./Spletno programiranje/Backend/Dockerfile
          push: true
          tags: serverless24/app:latest
          
      - name: Run Docker container
        run: |
         docker run -d -p 3000:3000 --name my_app_container serverless24/app:latest
          
  notify:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Send webhook notification
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          headers: '{"Content-Type":"application/json"}'
          body: '{"text":"Docker image build and push succeeded!"}'
          github_event_payload: true
